version: "3.9"

services:
  zip-worker:
    build: .
    container_name: zip-worker
    restart: unless-stopped
    ports:
      - "4005:4005"
    environment:
      NODE_ENV: production
      PORT: 4005
      # add any other env vars here